### ISSUE TITLE
"File not found" on $TMP/QMRIToolsReg/result-3D.nii.gz.

### ISSUE THREAD

**Issue by rljacobson** [mfroeling/QMRITools#10]
**Describe the bug**
`RegisterData`, `RegisterDataTransformSplit`, `RegisterDataSplit` fail with an import error. It cannot find `result-3D.nii.gz` in the temporary directory.

**To Reproduce**
1. Open the `demo.nb` file and initialize.
2. Scroll to the Registration using Elastix section and import the data.
3. Continue evaluating the code cells under Affine Transformation until you get to `RegisterData` which will fail with an error.

**Desktop (please complete the following information):**
 - OS: macOS
 - Mathematica version 11.3

Other functions in the `Register*` family fail with the same error. Of course, any demonstration code depending on the output of these functions also fail. 

<img width="991" alt="screen shot 2019-02-11 at 12 23 47 am" src="https://user-images.githubusercontent.com/1412598/53453715-e6e2c180-39f2-11e9-840a-e7a6ddd635bd.png">
<img width="973" alt="screen shot 2019-02-11 at 12 25 08 am" src="https://user-images.githubusercontent.com/1412598/53453721-ea764880-39f2-11e9-95ba-3c79063f48ff.png">

**Comment by mfroeling** [comment]
Indeed the mac compatibility has some issues at the moment. I was aware of this and working on a fix with some collaborators. Currently i don't have any mac system available for testing. 

I am working on a full revision of the registrtation framework such that it will be compatible with both linux and Max. currently the software generates windows command line functions and bat files. these have to be converted to bash.

I will let you know when this issue is fixed but i might take a while.

**Comment by mfroeling** [comment]
Unix and Mac compatibility should be OK now, the code is changed still need tot test it. will know more next week.

**Comment by mfroeling** [comment]
I have validated the mac and unix compatibility.
For future readers if any new issues arise please let me know
