### ISSUE TITLE
add literature references for the methods used

### ISSUE THREAD

**Issue by grlee77** [mfroeling/QMRITools#7]
**Is your feature request related to a problem? Please describe.**

Functions and arguments in the libarry tend to be clearly named, but documentation on the underlying implementations used are lacking.  For basic manipulations/visualization functions this is not an issue as they are pretty self-explanatory, but for a number of other functions it would be helpful to specify a reference for the implementation. This can be as simple as a single paragraph summary and/or a link to a corresponding publication.

**Describe the solution you'd like**

It would be helpful to have the following
- A literature reference (ideally including the paper DOI) corresponding to the method implemented.
- If the implementation differs substantially from what is described, provide a brief summary of the difference and rationale behind it.

**Describe alternatives you've considered**

**Additional context**

As a concrete example from `DixonTools.nb`. A description provided is:
``DixonReconstruct \[LongDash] Performs Dixon reconstruction of real and imaginary data.``

From the name of that function, I would not know if it is performing basic two-point Dixon, IDEAL fat/water estimation or one of a number of other potential approaches based on graph-cuts, etc.? Inspection of the code reveals that it appears to be IDEAL with support for a multi-peak fat model and involves iterative potentially accounting for off-resonance and T2* decay. A potential user should be able to quickly infer what method is going to be applied without having to read the underlying source code.

**Comment by mfroeling** [comment]
Hi indeed that is lacking but can easily be added. 

I like you suggestion to add paragraphs to the guide pages of the documentation with links to the DOI of the manuscripts (since i like my function help to be as clear as possible). 

I will only do this for the main processing functions scuh as T2 fitting dixon reconstruction denoising etc. that have a solid basis in literature. 

I will let you know when they are updated.

**Comment by grlee77** [comment]
A couple of other random things I noticed when looking over the code:

1.) PhysioTools: What format(s) of physiology log files is this supposed to process? I think each vendor uses their own format for respiratory, ECG and/or PPU logs.

2.) I saw the term "Overplus" in relation to diffusion gradients. Isn't this a Philips-specific term to refer to gradients played out along a combination of the X/Y/Z axes to allow shorter echo times at a given b-value? I'm not sure users coming from other systems would know what that is referring to.

**Comment by mfroeling** [comment]
@grlee77 i have added around 20 dois troughout the guides in the documentations, it is currently compiling and will upload it once it is done. for completeness i have also generated a PDF of the function documentation such that is readable outside mathematica.
https://github.com/mfroeling/QMRITools/blob/master/QMRITools/All-Functions.pdf
With the  new paper i tried to make clear what is and what is not in the demo file, since some tools such as the physlogging i hardly ever use my self. 

indeed adding what input (1D, 2D, 3D or 4D) for each function and what units would make some more clear. However the full documentation is allmost 100 pages so i have to see if i can find the time (and willingness) to go through all and figure out where such additions are needed. 

1) yes every vendor uses their own format for phys logging. Im not even sure if the current fucntion stille works on the latest philips log. I havent used the functionality in a while.
2) indeed overpuls is a term i adopted from the philips platform, and is used in generateGradient(GUI) not sure how else to call or explain this, but the visual representation of the gradients show what it is.

**Comment by grlee77** [comment]
Thanks for adding the DOIs.  Having a PDF is nice for reference outside of Mathematica. I don't know if exporting to HTML is similarly easy, but hosting the docs somewhere that they get indexed by Google, etc., might help potential users find your software.

As far as adding dimensions/units, perhaps just start with a few of the main functions likely to be of interest to end users such as Dixon, T2 fitting and DTI? (I am not saying you HAVE to do this for purposes of the review, it is just a suggestion to improve usability).

**Comment by mfroeling** [comment]
@grlee77 will defininatly add this for the main functions. Yes i can generate an html for the documentation using the mathematica workbench, and will see if it is possible to host this online with the repository.

**Comment by grlee77** [comment]
I see the DOIs were added to various files in your recent commit to master, but I do not see them in the PDF you linked above. Was that built prior to adding them or am I missing something?

**Comment by mfroeling** [comment]
@grlee, indeed i have updated the guide pages which are not included in the PDF. im working on the function files this week including the units where apropirate and also including the DOI on a function level.

once done i well recompile the help and regenerate the PDF which then should include the DOIs.

**Comment by mfroeling** [comment]
@grlee the DOI numbers are now also included in the code as well as in the documentation and PDF file. 
I still have to do a recompile of the reference page database and will see if the HTML build works.

adding units to the help files is next on my list.

**Comment by mfroeling** [comment]
@grlee i have created a new release that also includ a html version of the documentation, I have also added all DOIs and units of the parameters where apropriate.

https://github.com/mfroeling/QMRITools/releases/tag/2.1
